-- MySQL Script generated by MySQL Workbench
-- Sun Aug 11 02:02:50 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


CREATE SCHEMA IF NOT EXISTS mydb DEFAULT CHARACTER SET utf8 ;
USE mydb ;

-- -----------------------------------------------------
-- Table User
-- -----------------------------------------------------
CREATE TABLE User (
user_id SERIAL PRIMARY KEY,
user_name VARCHAR(45) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
is_acive BOOLEAN NOT NULL DEFAULT True
);


-- -----------------------------------------------------
-- Table Account_type
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Account_type (
  account_type_id SERIAL PRIMARY KEY,
  description VARCHAR(45) NOT NULL
);


-- -----------------------------------------------------
-- Table Account
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Account (
  account_id SERIAL PRIMARY KEY,
  user_id INT NOT NULL,
  account_type_id INT NOT NULL,
  amount double precision NOT NULL,
  debt double precision NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT True,
  CONSTRAINT fk_Account_User
    FOREIGN KEY (user_id)
    REFERENCES userssssss (user_id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Account_Account_type1
    FOREIGN KEY (account_type_id)
    REFERENCES Account_type (account_type_id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX fk_Account_User_idx ON Account (user_id);

CREATE INDEX fk_Account_Account_type1_idx ON Account (account_type_id);

INSERT INTO Account_type VALUES (1, 'debit');
INSERT INTO Account_type VALUES (2, 'credit');

